### ISSUE TITLE
Linux compatability

### ISSUE THREAD

**Issue by OmniLiquid** [Anskiy/wingsoftime#2]
The randomizer throws a file not found error when running on debian. I was able to fix it by changing the file paths in randomizer.py to use forward slashes rather than backslashes.Another possibility would be to use the path building functions in python or to just have everything in the sourcefiles folder, since I don't know if the forward slashes would be fine in Windows or not (though my research points to them being fine).

**Comment by Anskiy** [comment]
I thought I had solved this issue a while ago. It was certainly reported by a Mac user before. I'll check it again.

**Comment by Anskiy** [comment]
Hmm, in the current version of randomizer.py, I use forward slashes. Are you running an old version?

**Comment by OmniLiquid** [comment]
Ah, I see that now. I was going from the release version. I'll try the current version when I get home.
